# Site settings
theme: jekyll-theme-minimal
title: Jonathan W. Roberts
description: Bookmark this to keep an eye on all my project updates!
url: https://jwr42.github.io
baseurl: 
email: jonathan.w.roberts@pm.me
github_username:  jwr42

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/