project:
  type: website
  output-dir: docs

language: 
  search-text-placeholder: Search

website:
  title: "Jonathan Roberts"
  navbar:
    pinned: true
    left:
      - projects.qmd
  search: 
    keyboard-shortcut: ["?"]
    location: navbar
    type: textbox
  page-footer:
    center: 
      - text: "&copy; 2025 Jonathan Roberts"

format:
  html:
    theme: 
      light: flatly
    css: styles.css
    toc: false




